version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=notee
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - noteenet
    volumes:
      - postgres_notee:/var/lib/postgresql
      - postgres_notee_data:/var/lib/postgresql/data

  api:
    image: notee-api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notee
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - NOTEE_AUTH_TOKEN_CHECKTOKENENDPOINTURL=http://auth:8081/oauth/check_token
    networks:
      - noteenet

  auth:
    image: notee-auth
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/notee
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - noteenet

networks:
  noteenet:
    driver: bridge

volumes:
  postgres_notee:
  postgres_notee_data:
