server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notee
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: lama.pizama.git@gmail.com
    password: kmaltsspcezbfzei
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000
notee:
  auth:
    token:
      check-token-endpoint-url: http://localhost:8081/oauth/check_token
    client:
      client-id: js_client
      client-secret: secret

