server:
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notee
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: lama.pizama.git@gmail.com
    password: kmaltsspcezbfzei
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-out:
          destination: events
        event-in:
          destination: events
          group: events-consumer
notee:
  auth:
    token:
      check-token-endpoint-url: http://localhost:8081/oauth/check_token
      authorization-endpoint-url: http://localhost:8081/oauth/authorize
    js-client:
      client-id: js_client
      client-secret: secret
    swagger-client:
      client-id: swagger
      client-secret: secret

